apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: watcher-harbor-registry-secret-sync
  namespace: watcher-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: jcode-harbor-pull-secret
    kind: ClusterSecretStore
  target:
    name: watcher-harbor-registry-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  dataFrom:
    - extract:
        key: watcher-harbor-registry-secret
