apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher-course-reader
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watcher-course-metadata-reader
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: watcher-course-metadata-reader-production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: watcher-course-metadata-reader
subjects:
  - kind: ServiceAccount
    name: watcher-course-reader
    namespace: watcher
