apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend-pvc.yaml
  - backend-migration.yaml
  - backend.yaml
  - filemon-pvc.yaml
  - filemon-daemonset.yaml
  - filemon-service.yaml
  - filemon-servicemonitor.yaml
  - procmon-pvc.yaml
  - procmon-daemonset.yaml
  - procmon-service.yaml
